[package]
name = "crud-api-example"
version = "0.1.0"
edition = "2021"

[dependencies]
postgres = "0.19.9"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_derive = "1.0.215"